### ISSUE TITLE
x264 transfer error with BT.601

### ISSUE THREAD

**Issue by noizuy** [Jaded-Encoding-Thaumaturgy/vs-muxtools#7]
The following error occurs if a clip's transfer is set to BT.601
```
x264 [error]: invalid argument: transfer = bt601
```
Script:
```py
from vstools import vs, core
from vsmuxtools import x264

blank_clip = core.std.BlankClip(format=vs.YUV420P8)
video = x264().encode(blank_clip)
```
In this case, x264 gets passed "--transfer bt601", which it doesn't know.

**Comment by Vodes** [comment]
from the looks of it, this only worked because of a [bug in vstools](https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools/blob/71a60d582de6a8c7aceab44dce99da8b328e7ca4/vstools/enums/color.py#L1142) (that was still in there at the time of rewriting the vsmuxtools logic) but considering the map isn't used in any code it's gonna be restored now.

**Comment by Vodes** [comment]
https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools/commit/1bc635f4ffedcc113c877acca8802b673ae5c650
